englishToJavaScript = [
    [["<<foo>> sorted in order of decreasing length"], "<<foo>>.sort(function(a, b){ return a.length - b.length; })", "final"],
    [["[ <<foo>> ]"], "[<<foo>>]", "final"],
    [["<<foo>> sorted in order of descending length"], "<<foo>>.sort(function(a, b){ return b.length - a.length; })", "final"],
    [["<<foo>> ;"], "<<foo>>;", "final"],
    [["var <<foo>> = <<bar>>", "var <<foo>> = <<bar>> ;"], "var <<foo>> = <<bar>>", "final"],
    [["<<foo>> = <<bar>>"], "<<foo>> = <<bar>>", "final"],
    [["<<foo>> += <<bar>>"], "foo += <<bar>>", "final"],
    [["<<goo>> ++"], "<<goo>>++", "final"],
    [["<<goo>> --"], "<<goo>>--", "final"],
    [["def <<foo>> <<bar>> <<baz>>"], "function <<foo>>(<<bar>>){ <<baz>> }", "final"],
    [["def <<foo>> <<bar>>"], "function <<foo>>(){ <<bar>> }", "final"],
    [["return <<foo>>"], "return <<foo>>", "final"],
    [["<<foo>> { <<bar>> }"], "<<foo>>(<<bar>>)", "final"],
    [["<<bar>> {}"], "<<bar>>()", "final"],
    [["for <<foo>> in <<bar>> <<baz>>"], "<<bar>>.forEach(function(<<foo>>) { <<baz>> });", "final"],
    [["while <<foo>> <<bar>>"], "while <<foo>>{ <<bar>> }", "final"],
    [["if <<foo>> <<bar>>"], "while <<foo>>{ <<bar>> }", "final"],
    [["not <<foo>>"], "!<<foo>>>", "final"],
    [["until <<foo>> <<bar>>"], "while (not <<foo>>) <<bar>>"],
    [["<<foo>> = { <<bar>>"], "<<foo>> = { <<bar>>", "final"],
    [["<<foo>> : <<bar>>"], "<<foo>>:<<bar>>", "final"],
    [["<<foo>> ,"], "<<foo>>,", "final"],
    [["<<foo>> : <<bar>> ,"], "(<<foo>> : <<bar>>) ,"],
    [["twice <<foo>>"], "2 * <<foo>>"],
    [["thrice <<foo>>"], "3 * <<foo>>"],
]

